### ISSUE TITLE
Always have to "Pause" for this particular website

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kbjorgensen/kbsslenforcer#111] opened 2015-03-21 17:02 UTC
```
What steps will reproduce the problem?
1. Go here: 
http://www.programme-tv.net/videos/extraits/34298-oups-le-premier-acheteur-de-l-
iphone-6-le-fait-tomber-en-direct-a-la-tele/
2. To be sure you're able to play the video, deactivate adblock, donottrackme 
etc

What is the expected output? What do you see instead?
I see this: http://i.imgur.com/TRuRJxc.png
I think KB-SSL tries to enforce a non SSL page (an advertise maybe) and if we 
know the domain of this external page he tries to load, I'm pretty sure we can 
fix this issue by "Ignoring" this page.
If I "Pause" the KB-SSL extension I can see the video with no more issue (even 
with adblock, donottrackme etc) http://i.imgur.com/HfjoDRH.png

What version of the product are you using? On what operating system?
I'm using Chrome Version 39.0.2159.4 dev-m on Win 8.1 x64 and KB SSL Enforcer 
2.0.4.

Please provide any additional information below.
Thanks in advance and sorry, English ain't my native language.
```

Original issue reported on code.google.com by `truethro...@gmail.com` on 19 Sep 2014 at 1:57

**Comment by kbjorgensen** [comment] 2015-03-21 18:38
Closing the issue since it couldn't be reproduced.

**Closed by kbjorgensen** 2015-03-21 18:38 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
